version: '3'
services:
  db:
    ports:
    - 5432:5432
    image: postgres:10.2-alpine
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "ca"
      POSTGRES_USER: "ca"
      POSTGRES_DB: "cggdb"
